const { isProd } = require('../utils/isProd')

const restrictedPackages = ['moment']

module.exports = {
  'no-constant-condition': ['warn', { checkLoops: false }],
  'no-debugger': !isProd() ? 'off' : 'error',
  'no-console': !isProd() ? 'off' : 'error',
  'no-fallthrough': 'off',
  'max-params': ['warn', 3],
  curly: 'off',
  'default-case-last': 'error',
  eqeqeq: ['error', 'smart'],
  'max-classes-per-file': 'warn',
  'max-depth': 'warn',
  'max-nested-callbacks': 'warn',
  'no-caller': 'error',
  'no-else-return': 'warn',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'warn',
  'no-extra-boolean-cast': 'warn',
  'no-extra-semi': 'warn',
  'no-implied-eval': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'warn',
  'no-lonely-if': 'warn',
  'no-nested-ternary': 'warn',
  'no-new': 'warn',
  'no-octal': 'warn',
  'no-param-reassign': 'error',
  'no-return-await': 'warn',
  'no-throw-literal': 'warn',
  'no-undef-init': 'warn',
  'no-unneeded-ternary': 'warn',
  'no-useless-catch': 'warn',
  'no-useless-rename': 'warn',
  'no-useless-return': 'warn',
  'no-var': 'error',
  'prefer-const': 'warn',
  'prefer-rest-params': 'warn',
  'prefer-spread': 'warn',
  'prefer-object-spread': 'warn',
  'prefer-template': 'warn',
  'quote-props': ['error', 'as-needed'],
  'require-await': 'warn',
  'require-yield': 'warn',
  'spaced-comment': ['warn', 'always'],
  'brace-style': 'warn',
  'eol-last': 'warn',
  'linebreak-style': 'warn',
  'no-extra-parens': 'warn',
  'no-mixed-spaces-and-tabs': 'warn',
  'no-multi-spaces': 'warn',
  'no-multiple-empty-lines': 'warn',
  'default-param-last': 'error',
  'no-empty-function': 'warn',
  'no-restricted-imports': ['warn', ...restrictedPackages],
  'no-unused-vars': ['error', { ignoreRestSiblings: true }],
  indent: 'off',

  // imports
  'import/no-absolute-path': 'error',
  'import/no-webpack-loader-syntax': 'error',
  'import/no-self-import': 'off', // performance issues
  'import/no-cycle': 'off', // performance issues
  'import/no-deprecated': 'off', // performance issues
  'import/no-mutable-exports': 'warn',
  'import/first': 'warn',
  'import/exports-last': 'off',
  'import/order': 'off',
  'import/newline-after-import': 'warn',
  'import/no-default-export': 'error',

  // security
  'security/detect-buffer-noassert': 'error',
  'security/detect-disable-mustache-escape': 'error',
  'security/detect-eval-with-expression': 'error',
  'security/detect-no-csrf-before-method-override': 'error',
  'security/detect-non-literal-fs-filename': 'warn',
  'security/detect-non-literal-require': 'warn',
}
