// //autogenerated by /build-version.js PLEASE, DO NOT MODIFY!!!
export const buildVersion = {
  appName: 'Coinote',
  version: '5.0.1',
  changeset: 'b03faa4ac50ed0b9cd59ea91675c611c012ab289',
  buildTime: new Date(1654438137927), // 'Sun Jun 05 2022 17:08:57 GMT+0300 (Москва, стандартное время)',
}
