// //autogenerated by /build-version.js PLEASE, DO NOT MODIFY!!!
export const buildVersion = {
  appName: 'Coinote',
  version: '5.0.1',
  changeset: '701d783c0e28bea173da7c1b50dd0bf7e520067d',
  buildTime: new Date(1657447459374), // 'Sun Jul 10 2022 13:04:19 GMT+0300 (Москва, стандартное время)',
};
