// //autogenerated by /build-version.js PLEASE, DO NOT MODIFY!!!
export const buildVersion = {
  appName: 'Coinote',
  version: '5.0.1',
  changeset: '2190b9a76ce9a2888e2ca811d0a9754302cde69e',
  buildTime: new Date(1663101560551), // 'Tue Sep 13 2022 23:39:20 GMT+0300 (Москва, стандартное время)',
}
